import { useEffect, useState } from 'react';
import { api } from '../lib/supabase';
import Spinner from '../components/Spinner';
import AdminLayout from '../components/AdminLayout';
import AdminTabs from '../components/AdminTabs';
import PeopleTab from '../components/PeopleTab';
import RoomsTab from '../components/RoomsTab';
import FloorPlansTab from '../components/FloorPlansTab';
import { useAuth } from '../context/AuthContext';

const blankUser = { full_name:'', email:'', password:'', role:'user', is_active:true };
const blankRoom = { name:'', building_name:'', floor:'', room_number:'', type:'Meeting room', capacity:1, equipment:'', description:'', is_active:true, floor_plan_id:'', map_x:'', map_y:'' };
const blankPlan = { name:'', building_name:'', floor:'', image_url:'' };
const message = (text, type='success') => ({text,type});

export default function Admin() {
  const { user } = useAuth();
  const [tab,setTab]=useState('users'); const [users,setUsers]=useState([]); const [rooms,setRooms]=useState([]); const [plans,setPlans]=useState([]); const [editing,setEditing]=useState(null); const [form,setForm]=useState({}); const [notice,setNotice]=useState(null); const [loading,setLoading]=useState(true); const [deleteTarget,setDeleteTarget]=useState(null);
  const load=async()=>{setLoading(true);try{const [userData,roomData,planData]=await Promise.all([api('/users'),api('/rooms?admin=true'),api('/floor-plans')]);setUsers(userData);setRooms(roomData);setPlans(planData);}catch(e){setNotice(message(e.message,'error'));}finally{setLoading(false)}};
  useEffect(()=>{async function loadData(){await load()}loadData();},[]);
  const open=(kind,item)=>{setEditing(kind);if(kind==='user')setForm(item?{...item,password:''}:blankUser);if(kind==='room')setForm(item?{...item,equipment:(item.equipment||[]).join(', '),floor_plan_id:item.floor_plan_id||'',map_x:item.map_x??'',map_y:item.map_y??''}:blankRoom);if(kind==='plan')setForm(item||blankPlan);};
  const change=(event)=>setForm({...form,[event.target.name]:event.target.type==='checkbox'?event.target.checked:event.target.value});
  const submit=async(event)=>{event.preventDefault();try{const wasEdit=Boolean(form.id);let toast='Saved successfully.';if(editing==='user'){const body={...form};if(!body.password)delete body.password;await api(wasEdit?`/users/${form.id}`:'/users',{method:wasEdit?'PATCH':'POST',body:JSON.stringify(body)});toast=wasEdit?'User updated successfully.':'User created successfully.';}if(editing==='room'){const body={...form,capacity:Number(form.capacity),equipment:form.equipment.split(',').map(x=>x.trim()).filter(Boolean),floor_plan_id:form.floor_plan_id||null,map_x:form.map_x===''?null:Number(form.map_x),map_y:form.map_y===''?null:Number(form.map_y)};await api(wasEdit?`/rooms/${form.id}`:'/rooms',{method:wasEdit?'PATCH':'POST',body:JSON.stringify(body)});toast=wasEdit?'Room updated successfully.':'Room created successfully.';}if(editing==='plan'){await api(wasEdit?`/floor-plans/${form.id}`:'/floor-plans',{method:wasEdit?'PATCH':'POST',body:JSON.stringify(form)});}setNotice(message(toast));setEditing(null);setForm({});await load();}catch(e){setNotice(message(e.message,'error'));}};
  const remove=async(kind,item)=>{if(!confirm(`${kind==='user'?'Deactivate':'Deactivate'} ${item.name||item.full_name}? This can be changed later.`))return;try{if(kind==='user')await api(`/users/${item.id}`,{method:'PATCH',body:JSON.stringify({is_active:false})});else await api(`/rooms/${item.id}`,{method:'DELETE'});setNotice(message(kind==='room'?'Room deleted successfully.':'User deactivated successfully.'));await load();}catch(e){setNotice(message(e.message,'error'));}};
  const deleteUser=async()=>{if(!deleteTarget)return;try{await api(`/users/${deleteTarget.id}`,{method:'DELETE'});setNotice(message('User deleted successfully.'));setDeleteTarget(null);await load();}catch(e){setNotice(message(e.message,'error'));setDeleteTarget(null);}};
  const deleteFloorPlan=async(plan)=>{if(!confirm(`Delete ${plan.name}?`))return;try{await api(`/floor-plans/${plan.id}`,{method:'DELETE'});setNotice(message('Floor plan deleted successfully.'));await load();}catch(e){setNotice(message(e.message,'error'));}};
  const resetUserPassword=async(user)=>{if(!confirm(`Send a password reset email to ${user.email}?`))return;try{await api(`/users/${user.id}/password-reset`,{method:'POST'});setNotice(message('Password reset email sent successfully.'));}catch(e){setNotice(message(e.message,'error'));}};
  const upload=async(event)=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{const data=await api('/floor-plans/upload',{method:'POST',body:JSON.stringify({image_data:reader.result})});setForm(current=>({...current,image_url:data.image_url}));setNotice(message('Floor plan image uploaded.'));}catch(e){setNotice(message(e.message,'error'));}};reader.readAsDataURL(file);};
  if(loading)return <Spinner/>;
  const closeEditor=()=>{setEditing(null);setForm({});};const switchTab=(next)=>{setTab(next);setEditing(null);setForm({});setDeleteTarget(null);setNotice(null);};return <AdminLayout notice={notice} tabs={<AdminTabs activeTab={tab} onChange={switchTab}/>}>{tab==='users'&&<PeopleTab users={users} currentUserId={user?.id} onOpen={open} onRemove={remove} onDelete={setDeleteTarget} onResetPassword={resetUserPassword}/>} {tab==='rooms'&&<RoomsTab rooms={rooms} onOpen={open} onRemove={remove}/>} {tab==='plans'&&<FloorPlansTab plans={plans} onOpen={open} onDelete={deleteFloorPlan}/>} {editing==='room'&&<RoomModal form={form} plans={plans} change={change} close={closeEditor} submit={submit}/>} {editing&&editing!=='room'&&<Editor kind={editing} form={form} plans={plans} change={change} close={closeEditor} submit={submit} upload={upload}/>} {deleteTarget&&<DeleteUserModal user={deleteTarget} onCancel={()=>setDeleteTarget(null)} onConfirm={deleteUser}/>}</AdminLayout>;
}
function AdminTable({headers,rows}){return <div className="table-wrap"><table><thead><tr>{headers.map(head=><th key={head}>{head}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table></div>}
function Editor({kind,form,plans,change,close,submit,upload}){const title=form.id?`Edit ${kind}`:`Add ${kind==='plan'?'floor plan':kind}`;return <div className="modal-backdrop"><form className="modal card" onSubmit={submit}><div className="section-head"><h3>{title}</h3><button type="button" onClick={close}>Close</button></div>{kind==='user'&&<><Field label="Full name" name="full_name" value={form.full_name} change={change}/><Field label="Email" name="email" type="email" value={form.email} change={change}/><Field label={form.id?'New password (optional)':'Temporary password'} name="password" type="password" value={form.password} change={change} required={!form.id}/><label>Role<select name="role" value={form.role} onChange={change}><option value="user">User</option><option value="admin">Admin</option></select></label><Check label="Account is active" name="is_active" checked={form.is_active} change={change}/></>}{kind==='room'&&<><div className="form-row"><Field label="Room name" name="name" value={form.name} change={change}/><Field label="Room number" name="room_number" value={form.room_number} change={change}/></div><div className="form-row"><Field label="Building" name="building_name" value={form.building_name} change={change}/><Field label="Floor" name="floor" value={form.floor} change={change}/></div><div className="form-row"><Field label="Room type" name="type" value={form.type} change={change}/><Field label="Capacity" name="capacity" type="number" value={form.capacity} change={change}/></div><Field label="Equipment (comma separated)" name="equipment" value={form.equipment} change={change}/><label>Description<textarea name="description" value={form.description} onChange={change}/></label><label>Floor plan<select name="floor_plan_id" value={form.floor_plan_id} onChange={change}><option value="">Not assigned</option>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.building_name} · {plan.floor}</option>)}</select></label><div className="form-row"><Field label="Map X (0–100)" name="map_x" type="number" value={form.map_x} change={change}/><Field label="Map Y (0–100)" name="map_y" type="number" value={form.map_y} change={change}/></div><Check label="Room is available" name="is_active" checked={form.is_active} change={change}/></>}{kind==='plan'&&<><Field label="Plan name" name="name" value={form.name} change={change}/><div className="form-row"><Field label="Building" name="building_name" value={form.building_name} change={change}/><Field label="Floor" name="floor" value={form.floor} change={change}/></div><label>Upload floor plan image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></label><Field label="Image URL" name="image_url" type="url" value={form.image_url} change={change}/>{form.image_url&&<img className="plan-preview" src={form.image_url} alt="Floor plan preview"/>}</>}<button className="primary full">Save {kind}</button></form></div>}
function Field({label,name,value,change,type='text',required=true}){return <label>{label}<input name={name} type={type} value={value??''} onChange={change} required={required}/></label>}
function Check({label,name,checked,change}){return <label className="check"><input type="checkbox" name={name} checked={Boolean(checked)} onChange={change}/>{label}</label>}
function RoomModal({form,plans,change,close,submit}){return <div className="modal-backdrop"><form className="modal card room-modal" onSubmit={submit}><div className="section-head"><div><h3>{form.id?'Edit room':'Add room'}</h3><p>Enter room details and availability.</p></div></div><div className="form-row"><Field label="Room Name" name="name" value={form.name} change={change}/><Field label="Room Number" name="room_number" value={form.room_number} change={change}/></div><div className="form-row"><Field label="Building" name="building_name" value={form.building_name} change={change}/><Field label="Floor" name="floor" value={form.floor} change={change}/></div><div className="form-row"><Field label="Capacity" name="capacity" type="number" value={form.capacity} change={change}/><Field label="Room Type" name="type" value={form.type} change={change}/></div><Field label="Equipment" name="equipment" value={form.equipment} change={change}/><label>Description<textarea name="description" value={form.description} onChange={change}/></label><label>Floor Plan Assignment<select name="floor_plan_id" value={form.floor_plan_id} onChange={change}><option value="">Not assigned</option>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.building_name} · {plan.floor}</option>)}</select></label><Check label="Room is active and available" name="is_active" checked={form.is_active} change={change}/><div className="modal-actions"><button type="button" className="button-quiet" onClick={close}>Cancel</button><button className="primary">Save Room</button></div></form></div>}
function DeleteUserModal({user,onCancel,onConfirm}){return <div className="modal-backdrop"><div className="delete-modal"><h3>Delete user?</h3><p><b>{user.full_name}</b> will be permanently removed. This action cannot be undone.</p><div><button className="button-quiet" onClick={onCancel}>Cancel</button><button className="delete-confirm" onClick={onConfirm}>Delete</button></div></div></div>}
